# Generated by Django 5.2.8 on 2025-12-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_assistantcategory_supportrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('tutor', 'Преподаватель'), ('admin', 'Администратор')], default='student', help_text='Выберите, как вы будете использовать платформу: как студент или как преподаватель', max_length=20, verbose_name='Роль на платформе'),
        ),
    ]
